SELECT DISTINCT ?entity ?entityLabel ?isin_value ?lei_value ?country ?countryLabel WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,de,fr,it". }
  {
    SELECT ?entity  WHERE {
      {
        ?entity p:P1278 ?legal_entity_statement . # Entities with legal entity identifier (LEI)
        ?entity p:P31 ?statement0 . # Entities which are instances of businesses or its subclasses
        ?statement0 (ps:P31/(wdt:P279*)) wd:Q4830453 .
      }
    }
  }
  OPTIONAL {
      ?entity p:P17 ?statement2 .
      ?statement2 ps:P17 ?country . # Country
  }
  OPTIONAL {
      ?entity (ps:P946) ?isin_prop .
      ?isin_prop (ps:P946) ?isin_value . # isin id
  }
  OPTIONAL {
      ?legal_entity_prop (p:P1278) ?lei_value .
  }
}
