# Query all DE,FR,IT firms listed as publicly traded or with ISIN number attached, add LEI identifier if available
SELECT ?company ?companyLabel ?isin_value ?lei_value WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,de,fr,it". }
  {
    {
      ?company p:P946 ?isin_prop.
      ?isin_prop (ps:P946) ?isin_value. # isin id
    }    
    OPTIONAL {
      ?company p:P1278 ?legal_identifier_id.
      ?legal_identifier_id (ps:P1278) ?lei_value.
    }
  }
}
