# Query all entities with legal entity identifiers (LEI)
SELECT DISTINCT ?company ?companyLabel ?isin_value ?lei_value ?country ?countryLabel WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,de,fr,it". }
  {
    ?entity p:P1278 ?legal_entity_id . # Entities with legal entity identifier (LEI)
    ?legal_entity_id p:P1278 ?lei_value .
  }
  OPTIONAL {
      ?company p:P17 ?statement2 .
      ?statement2 ps:P17 ?country . # Country
  }
  OPTIONAL {
      ?isin_prop (ps:P946) ?isin_value . # isin id
  }
}
