# Query all firms without LEI, but with ISIN attached
SELECT DISTINCT ?entity ?entityLabel ?isin_value ?country ?countryLabel ?country_alpha_2 WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,de,fr,it". }
  {
    ?entity p:P946 ?isin_prop . # Entities with ISIN
    ?isin_prop (ps:P946) ?isin_value . # ISIN  
    minus {?entity p:P1278 ?legal_entity_prop .}
  }
  OPTIONAL {
      ?entity p:P17 ?statement2 .
      ?statement2 ps:P17 ?country . # Country
      ?country p:P297 ?iso_two_letter .
      ?iso_two_letter ps:P297 ?country_alpha_2 .
  }
}
