---
on:
  push:
    branches: main
    paths:
      - docs/**
  pull_request:
    branches: main
    paths:
      - docs/**
  registry_package:
    types: [published, updated]
  workflow_dispatch:

name: Render and deploy Book

permissions:
  contents: write
  packages: read
  pages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    container: ghcr.io/trr266/esef-website:main
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4
      - 
        name: Pre-build image and run make ci-build in dev container
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/trr266/esef-website
          push: never
          runCmd: |
            export HOME=/root
            julia --project=docs setup_julia.jl
            quarto render docs --no-cache 
      - 
        name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/_book
