---
on:
  push:
    branches: main
    paths:
      - docs/**
  pull_request:
    branches: main
    paths:
      - docs/**
  registry_package:
    types: [published, updated]
  workflow_dispatch:

name: Render and deploy Book

permissions:
  contents: write
  packages: read
  pages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    container: ghcr.io/trr266/esef-website:main
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: Render book to all formats  
        run: |
          export HOME=/root
          julia --project=docs setup_julia.jl
          quarto render docs --no-cache 
      - 
        name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/_book
